IDENTIFICATION DIVISION.
PROGRAM-ID. TOPOLOGICAL-SORT.

DATA DIVISION.
WORKING-STORAGE SECTION.
01  N                   PIC 9(5).
01  M                   PIC 9(5).
01  I                   PIC 9(5).
01  J                   PIC 9(5).
01  U                   PIC 9(5).
01  V                   PIC 9(5).
01  COUNT               PIC 9(5).
01  CURRENT             PIC 9(5).
01  HAS-CYCLE           PIC 9 VALUE 0.

01  IN-DEGREE           OCCURS 100000 TIMES PIC 9(5).
01  VISITED             OCCURS 100000 TIMES PIC 9.
01  RESULT              OCCURS 100000 TIMES PIC 9(5).

01  EDGE-TABLE.
    05  EDGE-FROM       OCCURS 100000 TIMES PIC 9(5).
    05  EDGE-TO         OCCURS 100000 TIMES PIC 9(5).

01  QUEUE.
    05  Q-ITEM          OCCURS 100000 TIMES PIC 9(5).
01  Q-FRONT             PIC 9(5) VALUE 1.
01  Q-REAR              PIC 9(5) VALUE 0.

01  INPUT-LINE          PIC X(20).
01  OUTPUT-LINE         PIC X(10).

PROCEDURE DIVISION.
    ACCEPT INPUT-LINE.
    UNSTRING INPUT-LINE DELIMITED BY SPACE
        INTO N M.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
        MOVE 0 TO IN-DEGREE(I)
        MOVE 0 TO VISITED(I)
    END-PERFORM.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > M
        ACCEPT INPUT-LINE
        UNSTRING INPUT-LINE DELIMITED BY SPACE
            INTO U V
        MOVE U TO EDGE-FROM(I)
        MOVE V TO EDGE-TO(I)
        ADD 1 TO IN-DEGREE(V)
    END-PERFORM.
    
    MOVE 0 TO Q-REAR.
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
        IF IN-DEGREE(I) = 0
            ADD 1 TO Q-REAR
            MOVE I TO Q-ITEM(Q-REAR)
        END-IF
    END-PERFORM.
    
    MOVE 0 TO COUNT.
    MOVE 1 TO Q-FRONT.
    
    PERFORM UNTIL Q-FRONT > Q-REAR
        MOVE Q-ITEM(Q-FRONT) TO CURRENT
        ADD 1 TO Q-FRONT
        ADD 1 TO COUNT
        MOVE CURRENT TO RESULT(COUNT)
        
        PERFORM VARYING I FROM 1 BY 1 UNTIL I > M
            IF EDGE-FROM(I) = CURRENT
                SUBTRACT 1 FROM IN-DEGREE(EDGE-TO(I))
                IF IN-DEGREE(EDGE-TO(I)) = 0
                    ADD 1 TO Q-REAR
                    MOVE EDGE-TO(I) TO Q-ITEM(Q-REAR)
                END-IF
            END-IF
        END-PERFORM
    END-PERFORM.
    
    IF COUNT NOT = N
        DISPLAY "-1"
    ELSE
        PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
            MOVE RESULT(I) TO OUTPUT-LINE
            DISPLAY FUNCTION TRIM(OUTPUT-LINE)
        END-PERFORM
    END-IF.
    
    STOP RUN.
