IDENTIFICATION DIVISION.
PROGRAM-ID. EXPR-EVAL.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 INPUT-LINE PIC X(256).
01 INPUT-LEN PIC 9(3) VALUE 0.
01 POS PIC 9(3) VALUE 1.
01 RESULT PIC S9(9)V9(6).
01 DISPLAY-RESULT PIC -(9)9.9(6).

01 STACK-VALS.
   05 VAL-STACK OCCURS 100 TIMES PIC S9(9)V9(6).
01 VAL-TOP PIC 9(3) VALUE 0.

01 STACK-OPS.
   05 OP-STACK OCCURS 100 TIMES PIC X.
01 OP-TOP PIC 9(3) VALUE 0.

01 CURRENT-CHAR PIC X.
01 CURRENT-NUM PIC S9(9)V9(6).
01 NUM-STR PIC X(20).
01 NUM-LEN PIC 9(2) VALUE 0.
01 OP1 PIC S9(9)V9(6).
01 OP2 PIC S9(9)V9(6).
01 OP-CHAR PIC X.
01 TEMP-RESULT PIC S9(9)V9(6).
01 I PIC 9(3).

PROCEDURE DIVISION.
MAIN-PROCEDURE.
    ACCEPT INPUT-LINE.
    INSPECT INPUT-LINE TALLYING INPUT-LEN 
        FOR CHARACTERS BEFORE INITIAL SPACE.
    IF INPUT-LEN = 0
        MOVE 256 TO INPUT-LEN
        INSPECT INPUT-LINE REPLACING ALL X'00' BY SPACE
        INSPECT INPUT-LINE TALLYING INPUT-LEN 
            FOR CHARACTERS BEFORE INITIAL SPACE
    END-IF.
    
    MOVE 1 TO POS.
    MOVE 0 TO VAL-TOP.
    MOVE 0 TO OP-TOP.
    
    PERFORM PARSE-EXPR.
    
    MOVE VAL-STACK(VAL-TOP) TO DISPLAY-RESULT.
    DISPLAY DISPLAY-RESULT.
    STOP RUN.

PARSE-EXPR.
    PERFORM UNTIL POS > INPUT-LEN
        MOVE INPUT-LINE(POS:1) TO CURRENT-CHAR
        EVALUATE TRUE
            WHEN CURRENT-CHAR = ' '
                ADD 1 TO POS
            WHEN CURRENT-CHAR >= '0' AND CURRENT-CHAR <= '9'
                PERFORM READ-NUMBER
                ADD 1 TO VAL-TOP
                MOVE CURRENT-NUM TO VAL-STACK(VAL-TOP)
            WHEN CURRENT-CHAR = '('
                ADD 1 TO OP-TOP
                MOVE '(' TO OP-STACK(OP-TOP)
                ADD 1 TO POS
            WHEN CURRENT-CHAR = ')'
                PERFORM APPLY-UNTIL-OPEN-PAREN
                ADD 1 TO POS
            WHEN CURRENT-CHAR = '+' OR '-' OR '*' OR '/'
                PERFORM APPLY-HIGHER-PRECEDENCE
                ADD 1 TO OP-TOP
                MOVE CURRENT-CHAR TO OP-STACK(OP-TOP)
                ADD 1 TO POS
        END-EVALUATE
    END-PERFORM.
    
    PERFORM APPLY-REMAINING-OPS.

READ-NUMBER.
    MOVE 0 TO NUM-LEN.
    MOVE SPACES TO NUM-STR.
    PERFORM UNTIL POS > INPUT-LEN
        MOVE INPUT-LINE(POS:1) TO CURRENT-CHAR
        IF CURRENT-CHAR >= '0' AND CURRENT-CHAR <= '9'
            ADD 1 TO NUM-LEN
            MOVE CURRENT-CHAR TO NUM-STR(NUM-LEN:1)
            ADD 1 TO POS
        ELSE
            EXIT PERFORM
        END-IF
    END-PERFORM.
    MOVE FUNCTION NUMVAL(NUM-STR) TO CURRENT-NUM.

APPLY-HIGHER-PRECEDENCE.
    PERFORM UNTIL OP-TOP = 0
        MOVE OP-STACK(OP-TOP) TO OP-CHAR
        IF OP-CHAR = '('
            EXIT PERFORM
        END-IF
        IF (CURRENT-CHAR = '*' OR CURRENT-CHAR = '/') AND
           (OP-CHAR = '+' OR OP-CHAR = '-')
            EXIT PERFORM
        END-IF
        PERFORM APPLY-OP
    END-PERFORM.

APPLY-UNTIL-OPEN-PAREN.
    PERFORM UNTIL OP-TOP = 0
        MOVE OP-STACK(OP-TOP) TO OP-CHAR
        IF OP-CHAR = '('
            SUBTRACT 1 FROM OP-TOP
            EXIT PERFORM
        END-IF
        PERFORM APPLY-OP
    END-PERFORM.

APPLY-REMAINING-OPS.
    PERFORM UNTIL OP-TOP = 0
        PERFORM APPLY-OP
    END-PERFORM.

APPLY-OP.
    MOVE VAL-STACK(VAL-TOP) TO OP2.
    SUBTRACT 1 FROM VAL-TOP.
    MOVE VAL-STACK(VAL-TOP) TO OP1.
    MOVE OP-STACK(OP-TOP) TO OP-CHAR.
    SUBTRACT 1 FROM OP-TOP.
    
    EVALUATE OP-CHAR
        WHEN '+'
            ADD OP1 TO OP2 GIVING TEMP-RESULT
        WHEN '-'
            SUBTRACT OP2 FROM OP1 GIVING TEMP-RESULT
        WHEN '*'
            MULTIPLY OP1 BY OP2 GIVING TEMP-RESULT
        WHEN '/'
            DIVIDE OP1 BY OP2 GIVING TEMP-RESULT
    END-EVALUATE.
    
    MOVE TEMP-RESULT TO VAL-STACK(VAL-TOP).
