IDENTIFICATION DIVISION.
PROGRAM-ID. WORDFREQ.

DATA DIVISION.
WORKING-STORAGE SECTION.
01  INPUT-LINE          PIC X(10000).
01  LINE-LENGTH         PIC 9999 VALUE 0.
01  IDX                 PIC 9999 VALUE 1.
01  WORD-START          PIC 9999 VALUE 0.
01  WORD-END            PIC 9999 VALUE 0.
01  CURRENT-WORD        PIC X(1000).
01  WORD-LEN            PIC 9999 VALUE 0.
01  CHAR-AT-IDX         PIC X.

01  WORD-TABLE.
    05  WORD-ENTRY OCCURS 1000 TIMES INDEXED BY WI.
        10  WT-WORD     PIC X(1000).
        10  WT-COUNT    PIC 9999 VALUE 0.
        10  WT-ACTIVE   PIC 9 VALUE 0.

01  NUM-WORDS           PIC 9999 VALUE 0.
01  FOUND-FLAG          PIC 9 VALUE 0.
01  SEARCH-IDX          PIC 9999.

01  SORT-I              PIC 9999.
01  SORT-J              PIC 9999.
01  TEMP-WORD           PIC X(1000).
01  TEMP-COUNT          PIC 9999.

01  PRINT-LINE          PIC X(1100).

PROCEDURE DIVISION.
    ACCEPT INPUT-LINE.
    
    INSPECT INPUT-LINE TALLYING LINE-LENGTH 
        FOR CHARACTERS BEFORE INITIAL X'00'.
    
    IF LINE-LENGTH = 0
        INSPECT INPUT-LINE TALLYING LINE-LENGTH FOR ALL X'20'
        ADD 10000 TO ZERO GIVING LINE-LENGTH
        SUBTRACT LINE-LENGTH FROM 10000 GIVING LINE-LENGTH
    END-IF.
    
    PERFORM VARYING IDX FROM 1 BY 1 UNTIL IDX > LINE-LENGTH
        MOVE INPUT-LINE(IDX:1) TO CHAR-AT-IDX
        
        IF CHAR-AT-IDX NOT = SPACE
            IF WORD-START = 0
                MOVE IDX TO WORD-START
            END-IF
            MOVE IDX TO WORD-END
        ELSE
            IF WORD-START > 0
                PERFORM ADD-WORD
                MOVE 0 TO WORD-START
                MOVE 0 TO WORD-END
            END-IF
        END-IF
    END-PERFORM.
    
    IF WORD-START > 0
        PERFORM ADD-WORD
    END-IF.
    
    PERFORM BUBBLE-SORT.
    
    PERFORM VARYING SORT-I FROM 1 BY 1 UNTIL SORT-I > NUM-WORDS
        IF WT-ACTIVE(SORT-I) = 1
            STRING WT-WORD(SORT-I) DELIMITED BY '  '
                   ' ' DELIMITED BY SIZE
                   WT-COUNT(SORT-I) DELIMITED BY SIZE
                   INTO PRINT-LINE
            END-STRING
            DISPLAY FUNCTION TRIM(PRINT-LINE)
        END-IF
    END-PERFORM.
    
    STOP RUN.

ADD-WORD.
    COMPUTE WORD-LEN = WORD-END - WORD-START + 1.
    MOVE INPUT-LINE(WORD-START:WORD-LEN) TO CURRENT-WORD.
    
    MOVE 0 TO FOUND-FLAG.
    PERFORM VARYING SEARCH-IDX FROM 1 BY 1 UNTIL SEARCH-IDX > NUM-WORDS
        IF WT-WORD(SEARCH-IDX) = CURRENT-WORD
            ADD 1 TO WT-COUNT(SEARCH-IDX)
            MOVE 1 TO FOUND-FLAG
            EXIT PERFORM
        END-IF
    END-PERFORM.
    
    IF FOUND-FLAG = 0
        ADD 1 TO NUM-WORDS
        MOVE CURRENT-WORD TO WT-WORD(NUM-WORDS)
        MOVE 1 TO WT-COUNT(NUM-WORDS)
        MOVE 1 TO WT-ACTIVE(NUM-WORDS)
    END-IF.

BUBBLE-SORT.
    PERFORM VARYING SORT-I FROM 1 BY 1 UNTIL SORT-I >= NUM-WORDS
        PERFORM VARYING SORT-J FROM 1 BY 1 
            UNTIL SORT-J > NUM-WORDS - SORT-I
            IF WT-COUNT(SORT-J) < WT-COUNT(SORT-J + 1) OR
               (WT-COUNT(SORT-J) = WT-COUNT(SORT-J + 1) AND
                WT-WORD(SORT-J) > WT-WORD(SORT-J + 1))
                MOVE WT-WORD(SORT-J) TO TEMP-WORD
                MOVE WT-COUNT(SORT-J) TO TEMP-COUNT
                MOVE WT-WORD(SORT-J + 1) TO WT-WORD(SORT-J)
                MOVE WT-COUNT(SORT-J + 1) TO WT-COUNT(SORT-J)
                MOVE TEMP-WORD TO WT-WORD(SORT-J + 1)
                MOVE TEMP-COUNT TO WT-COUNT(SORT-J + 1)
            END-IF
        END-PERFORM
    END-PERFORM.
