IDENTIFICATION DIVISION.
PROGRAM-ID. LONGEST-ZERO-SUBARRAY.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 N PIC 9(6).
01 I PIC 9(6).
01 J PIC 9(6).
01 ARRAY-VALS.
   05 ARR-ELEM PIC S9(10) OCCURS 200000 TIMES.
01 PREFIX-SUM PIC S9(18).
01 MAP-TABLE.
   05 MAP-ENTRY OCCURS 400002 TIMES.
      10 MAP-KEY PIC S9(18).
      10 MAP-VAL PIC 9(6).
      10 MAP-USED PIC 9.
01 HASH-IDX PIC 9(6).
01 TEMP-SUM PIC S9(18).
01 MAX-LEN PIC 9(6) VALUE 0.
01 CURR-LEN PIC 9(6).
01 HASH-BASE PIC 9(18) VALUE 1000000000000000000.
01 TEMP-CALC PIC 9(18).
01 INPUT-LINE PIC X(2000000).
01 LINE-POS PIC 9(7).
01 LINE-LEN PIC 9(7).
01 CHAR-VAL PIC X.
01 NUM-VAL PIC S9(10).
01 NUM-SIGN PIC S9.
01 IN-NUMBER PIC 9.

PROCEDURE DIVISION.
    ACCEPT N.
    ACCEPT INPUT-LINE.
    
    MOVE 1 TO LINE-POS.
    MOVE FUNCTION LENGTH(FUNCTION TRIM(INPUT-LINE)) TO LINE-LEN.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
        MOVE 0 TO NUM-VAL
        MOVE 1 TO NUM-SIGN
        MOVE 0 TO IN-NUMBER
        
        PERFORM UNTIL LINE-POS > LINE-LEN
            MOVE INPUT-LINE(LINE-POS:1) TO CHAR-VAL
            IF CHAR-VAL = ' ' OR CHAR-VAL = X'09'
                IF IN-NUMBER = 1
                    EXIT PERFORM
                END-IF
            ELSE IF CHAR-VAL = '-'
                MOVE -1 TO NUM-SIGN
                MOVE 1 TO IN-NUMBER
            ELSE
                COMPUTE NUM-VAL = NUM-VAL * 10 + 
                    (FUNCTION ORD(CHAR-VAL) - FUNCTION ORD('0'))
                MOVE 1 TO IN-NUMBER
            END-IF
            ADD 1 TO LINE-POS
        END-PERFORM
        
        COMPUTE ARR-ELEM(I) = NUM-VAL * NUM-SIGN
    END-PERFORM.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > 400002
        MOVE 0 TO MAP-USED(I)
    END-PERFORM.
    
    MOVE 0 TO MAP-KEY(200001).
    MOVE 0 TO MAP-VAL(200001).
    MOVE 1 TO MAP-USED(200001).
    
    MOVE 0 TO PREFIX-SUM.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
        ADD ARR-ELEM(I) TO PREFIX-SUM
        
        ADD PREFIX-SUM TO HASH-BASE GIVING TEMP-CALC
        DIVIDE TEMP-CALC BY 400001 GIVING J REMAINDER HASH-IDX
        ADD 1 TO HASH-IDX
        
        PERFORM UNTIL HASH-IDX > 400002
            IF MAP-USED(HASH-IDX) = 0
                MOVE PREFIX-SUM TO MAP-KEY(HASH-IDX)
                MOVE I TO MAP-VAL(HASH-IDX)
                MOVE 1 TO MAP-USED(HASH-IDX)
                EXIT PERFORM
            ELSE IF MAP-KEY(HASH-IDX) = PREFIX-SUM
                COMPUTE CURR-LEN = I - MAP-VAL(HASH-IDX)
                IF CURR-LEN > MAX-LEN
                    MOVE CURR-LEN TO MAX-LEN
                END-IF
                EXIT PERFORM
            END-IF
            
            ADD 1 TO HASH-IDX
            IF HASH-IDX > 400002
                MOVE 1 TO HASH-IDX
            END-IF
        END-PERFORM
    END-PERFORM.
    
    DISPLAY MAX-LEN.
    STOP RUN.
