IDENTIFICATION DIVISION.
PROGRAM-ID. IPV4VALIDATOR.

DATA DIVISION.
WORKING-STORAGE SECTION.
01  INPUT-STRING        PIC X(100).
01  STRING-LENGTH       PIC 999.
01  I                   PIC 999.
01  J                   PIC 999.
01  DOT-COUNT           PIC 9 VALUE 0.
01  SEGMENT-START       PIC 999.
01  SEGMENT-LENGTH      PIC 999.
01  SEGMENT-STR         PIC X(10).
01  SEGMENT-NUM         PIC 9(10).
01  VALID-FLAG          PIC 9 VALUE 1.
01  CHAR-VAL            PIC X.
01  HAS-DIGIT           PIC 9.
01  LEADING-ZERO        PIC 9.

PROCEDURE DIVISION.
    ACCEPT INPUT-STRING.
    
    INSPECT INPUT-STRING TALLYING STRING-LENGTH 
        FOR CHARACTERS BEFORE INITIAL SPACE.
    
    IF STRING-LENGTH = 0
        MOVE 0 TO VALID-FLAG
        GO TO PRINT-RESULT.
    
    MOVE 1 TO SEGMENT-START.
    MOVE 0 TO DOT-COUNT.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > STRING-LENGTH
        MOVE INPUT-STRING(I:1) TO CHAR-VAL
        IF CHAR-VAL = '.'
            ADD 1 TO DOT-COUNT
            COMPUTE SEGMENT-LENGTH = I - SEGMENT-START
            IF SEGMENT-LENGTH < 1 OR SEGMENT-LENGTH > 3
                MOVE 0 TO VALID-FLAG
                GO TO PRINT-RESULT
            END-IF
            MOVE INPUT-STRING(SEGMENT-START:SEGMENT-LENGTH) 
                TO SEGMENT-STR
            PERFORM VALIDATE-SEGMENT
            IF VALID-FLAG = 0
                GO TO PRINT-RESULT
            END-IF
            COMPUTE SEGMENT-START = I + 1
        ELSE
            IF CHAR-VAL < '0' OR CHAR-VAL > '9'
                MOVE 0 TO VALID-FLAG
                GO TO PRINT-RESULT
            END-IF
        END-IF
    END-PERFORM.
    
    IF DOT-COUNT NOT = 3
        MOVE 0 TO VALID-FLAG
        GO TO PRINT-RESULT.
    
    COMPUTE SEGMENT-LENGTH = STRING-LENGTH - SEGMENT-START + 1.
    IF SEGMENT-LENGTH < 1 OR SEGMENT-LENGTH > 3
        MOVE 0 TO VALID-FLAG
        GO TO PRINT-RESULT.
    
    MOVE INPUT-STRING(SEGMENT-START:SEGMENT-LENGTH) TO SEGMENT-STR.
    PERFORM VALIDATE-SEGMENT.
    
    PRINT-RESULT.
    DISPLAY VALID-FLAG.
    STOP RUN.

VALIDATE-SEGMENT.
    MOVE 0 TO HAS-DIGIT.
    MOVE 0 TO LEADING-ZERO.
    
    PERFORM VARYING J FROM 1 BY 1 UNTIL J > SEGMENT-LENGTH
        IF SEGMENT-STR(J:1) NOT = ' '
            ADD 1 TO HAS-DIGIT
            IF J = 1 AND SEGMENT-STR(J:1) = '0' 
                MOVE 1 TO LEADING-ZERO
            END-IF
        END-IF
    END-PERFORM.
    
    IF HAS-DIGIT = 0
        MOVE 0 TO VALID-FLAG
        EXIT PARAGRAPH.
    
    IF LEADING-ZERO = 1 AND SEGMENT-LENGTH > 1
        MOVE 0 TO VALID-FLAG
        EXIT PARAGRAPH.
    
    MOVE 0 TO SEGMENT-NUM.
    IF SEGMENT-LENGTH = 1
        COMPUTE SEGMENT-NUM = FUNCTION NUMVAL(SEGMENT-STR(1:1))
    ELSE IF SEGMENT-LENGTH = 2
        COMPUTE SEGMENT-NUM = FUNCTION NUMVAL(SEGMENT-STR(1:2))
    ELSE IF SEGMENT-LENGTH = 3
        COMPUTE SEGMENT-NUM = FUNCTION NUMVAL(SEGMENT-STR(1:3))
    END-IF.
    
    IF SEGMENT-NUM > 255
        MOVE 0 TO VALID-FLAG.
