IDENTIFICATION DIVISION.
PROGRAM-ID. SMALLEST-SUBSTRING.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 S PIC X(100).
01 K PIC 9(3).
01 S-LEN PIC 9(3).
01 I PIC 9(3).
01 J PIC 9(3).
01 START-POS PIC 9(3).
01 MIN-START PIC 9(3).
01 CURRENT-SUB PIC X(100).
01 MIN-SUB PIC X(100).
01 RESULT PIC X(100).

PROCEDURE DIVISION.
    ACCEPT S.
    ACCEPT K.
    
    MOVE FUNCTION LENGTH(FUNCTION TRIM(S)) TO S-LEN.
    
    MOVE 1 TO MIN-START.
    MOVE S(1:K) TO MIN-SUB.
    
    PERFORM VARYING I FROM 2 BY 1 UNTIL I > S-LEN - K + 1
        MOVE S(I:K) TO CURRENT-SUB
        IF CURRENT-SUB < MIN-SUB
            MOVE CURRENT-SUB TO MIN-SUB
            MOVE I TO MIN-START
        END-IF
    END-PERFORM.
    
    DISPLAY MIN-SUB.
    
    STOP RUN.
