IDENTIFICATION DIVISION.
PROGRAM-ID. CONNECTED-COMPONENTS.

DATA DIVISION.
WORKING-STORAGE SECTION.
01  N                   PIC 9(4).
01  M                   PIC 9(4).
01  GRID.
    05  GRID-ROW        OCCURS 1000 TIMES.
        10  GRID-CELL   PIC X OCCURS 1000 TIMES.
01  VISITED.
    05  VISITED-ROW     OCCURS 1000 TIMES.
        10  VISITED-CELL PIC 9 OCCURS 1000 TIMES.
01  I                   PIC 9(4).
01  J                   PIC 9(4).
01  COUNT               PIC 9(8) VALUE 0.
01  INPUT-LINE          PIC X(1000).
01  STACK.
    05  STACK-SIZE      PIC 9(8) VALUE 0.
    05  STACK-ENTRY     OCCURS 1000000 TIMES.
        10  STACK-ROW   PIC 9(4).
        10  STACK-COL   PIC 9(4).
01  CURR-ROW            PIC 9(4).
01  CURR-COL            PIC 9(4).
01  NEW-ROW             PIC 9(4).
01  NEW-COL             PIC 9(4).
01  DIR                 PIC 9.
01  DR                  PIC S9(2).
01  DC                  PIC S9(2).

PROCEDURE DIVISION.
    ACCEPT N.
    ACCEPT M.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
        ACCEPT INPUT-LINE
        PERFORM VARYING J FROM 1 BY 1 UNTIL J > M
            MOVE INPUT-LINE(J:1) TO GRID-CELL(I, J)
            MOVE 0 TO VISITED-CELL(I, J)
        END-PERFORM
    END-PERFORM.
    
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
        PERFORM VARYING J FROM 1 BY 1 UNTIL J > M
            IF GRID-CELL(I, J) = '#' AND VISITED-CELL(I, J) = 0
                ADD 1 TO COUNT
                PERFORM DFS
            END-IF
        END-PERFORM
    END-PERFORM.
    
    DISPLAY COUNT.
    STOP RUN.

DFS.
    MOVE 0 TO STACK-SIZE.
    ADD 1 TO STACK-SIZE.
    MOVE I TO STACK-ROW(STACK-SIZE).
    MOVE J TO STACK-COL(STACK-SIZE).
    MOVE 1 TO VISITED-CELL(I, J).
    
    PERFORM UNTIL STACK-SIZE = 0
        MOVE STACK-ROW(STACK-SIZE) TO CURR-ROW
        MOVE STACK-COL(STACK-SIZE) TO CURR-COL
        SUBTRACT 1 FROM STACK-SIZE
        
        PERFORM VARYING DIR FROM 1 BY 1 UNTIL DIR > 4
            EVALUATE DIR
                WHEN 1 MOVE -1 TO DR MOVE 0 TO DC
                WHEN 2 MOVE 1 TO DR MOVE 0 TO DC
                WHEN 3 MOVE 0 TO DR MOVE -1 TO DC
                WHEN 4 MOVE 0 TO DR MOVE 1 TO DC
            END-EVALUATE
            
            COMPUTE NEW-ROW = CURR-ROW + DR
            COMPUTE NEW-COL = CURR-COL + DC
            
            IF NEW-ROW >= 1 AND NEW-ROW <= N AND
               NEW-COL >= 1 AND NEW-COL <= M AND
               GRID-CELL(NEW-ROW, NEW-COL) = '#' AND
               VISITED-CELL(NEW-ROW, NEW-COL) = 0
                MOVE 1 TO VISITED-CELL(NEW-ROW, NEW-COL)
                ADD 1 TO STACK-SIZE
                MOVE NEW-ROW TO STACK-ROW(STACK-SIZE)
                MOVE NEW-COL TO STACK-COL(STACK-SIZE)
            END-IF
        END-PERFORM
    END-PERFORM.
