IDENTIFICATION DIVISION.
PROGRAM-ID. LIS.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 N PIC 9(4).
01 I PIC 9(4).
01 J PIC 9(4).
01 MAX-LEN PIC 9(4).
01 ARR OCCURS 1000 TIMES PIC S9(9).
01 DP OCCURS 1000 TIMES PIC 9(4).
01 INPUT-VAL PIC S9(9).
PROCEDURE DIVISION.
ACCEPT N.
PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
    ACCEPT ARR(I)
END-PERFORM.
PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
    MOVE 1 TO DP(I)
END-PERFORM.
PERFORM VARYING I FROM 2 BY 1 UNTIL I > N
    PERFORM VARYING J FROM 1 BY 1 UNTIL J >= I
        IF ARR(J) < ARR(I)
            IF DP(J) + 1 > DP(I)
                COMPUTE DP(I) = DP(J) + 1
            END-IF
        END-IF
    END-PERFORM
END-PERFORM.
MOVE 0 TO MAX-LEN.
PERFORM VARYING I FROM 1 BY 1 UNTIL I > N
    IF DP(I) > MAX-LEN
        MOVE DP(I) TO MAX-LEN
    END-IF
END-PERFORM.
DISPLAY MAX-LEN.
STOP RUN.
