IDENTIFICATION DIVISION.
PROGRAM-ID. MAX-DISTINCT-CHARS.

DATA DIVISION.
WORKING-STORAGE SECTION.
01  INPUT-LINE          PIC X(1000).
01  BEST-LINE           PIC X(1000).
01  CHAR-TABLE          PIC X(256).
01  BEST-CHAR-TABLE     PIC X(256).
01  I                   PIC 9999 VALUE 0.
01  J                   PIC 999 VALUE 0.
01  DISTINCT-COUNT      PIC 999 VALUE 0.
01  MAX-DISTINCT        PIC 999 VALUE 0.
01  CHAR-POS            PIC 999.
01  CURRENT-CHAR        PIC X.
01  FOUND-FLAG          PIC 9 VALUE 0.
01  EOF-FLAG            PIC 9 VALUE 0.
01  LINE-LENGTH         PIC 9999.
01  FIRST-LINE-FLAG     PIC 9 VALUE 1.

PROCEDURE DIVISION.
MAIN-PROCEDURE.
    PERFORM UNTIL EOF-FLAG = 1
        INITIALIZE INPUT-LINE
        ACCEPT INPUT-LINE
            ON EXCEPTION
                MOVE 1 TO EOF-FLAG
            NOT ON EXCEPTION
                PERFORM COUNT-DISTINCT-CHARS
                IF DISTINCT-COUNT > MAX-DISTINCT OR FIRST-LINE-FLAG = 1
                    MOVE DISTINCT-COUNT TO MAX-DISTINCT
                    MOVE INPUT-LINE TO BEST-LINE
                    MOVE 0 TO FIRST-LINE-FLAG
                END-IF
        END-ACCEPT
    END-PERFORM
    
    IF FIRST-LINE-FLAG = 0
        DISPLAY BEST-LINE
    END-IF
    
    STOP RUN.

COUNT-DISTINCT-CHARS.
    MOVE SPACES TO CHAR-TABLE
    MOVE 0 TO DISTINCT-COUNT
    MOVE 1 TO I
    PERFORM VARYING I FROM 1 BY 1 UNTIL I > 1000
        MOVE INPUT-LINE(I:1) TO CURRENT-CHAR
        IF CURRENT-CHAR = LOW-VALUE OR CURRENT-CHAR = SPACE AND I > 1 AND INPUT-LINE(I - 1:1) = LOW-VALUE
            EXIT PERFORM
        END-IF
        MOVE 0 TO FOUND-FLAG
        PERFORM VARYING J FROM 1 BY 1 UNTIL J > 256 OR FOUND-FLAG = 1
            IF CHAR-TABLE(J:1) = CURRENT-CHAR
                MOVE 1 TO FOUND-FLAG
            END-IF
        END-PERFORM
        IF FOUND-FLAG = 0
            ADD 1 TO DISTINCT-COUNT
            MOVE CURRENT-CHAR TO CHAR-TABLE(DISTINCT-COUNT:1)
        END-IF
    END-PERFORM.
